config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy] do
    member do
      get :upvote
      get :downvote
    end
  end
  resources :replies, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validate  :picture_size

  private
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  include MicropostsHelper
  before_action :logged_in_user, only: [:create, :destroy, :upvote, :downvote]
  before_action :correct_user, only: :destroy
  before_action :votable, only: [:upvote, :downvote]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  # def like
  #   @micropost = Micropost.find(params[:id])
  #   @micropost.upvote += 1
  #   if @micropost.save
  #     redirect_to root_url
  #   else
  #     render 'static_pages/home'
  #   end
  # end

  def upvote
    create_new_vote
    @vote.up_or_down = true
    @micropost.upvote += 1
    if @micropost.save && @vote.save
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def downvote
    create_new_vote
    @vote.up_or_down = false
    @micropost.downvote += 1
    if @micropost.save && @vote.save
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

    def create_new_vote
      @micropost = Micropost.find(params[:id])
      @vote = Vote.new
      @vote.user = current_user
      puts @vote.inspect
      @vote.post_id = @micropost.id
      puts @vote.inspect
    end

    def votable
      unless votable?(params[:micropost_id])
        redirect_to root_url
      end
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def votable?(micropost_id)
    @vote = Vote.find_by_user_id_and_post_id(current_user.id, micropost_id)
    @vote.nil?
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if votable?(micropost.id) %>
      <%= link_to "upvote", upvote_micropost_path(micropost.id) %>,
      <%= link_to "downvote", downvote_micropost_path(micropost.id) %>,
    <% else %>
      voted,
    <% end %>
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>.
    <% end %>
    <% if micropost.upvote >= micropost.downvote %>
      Vote: <%= micropost.upvote - micropost.downvote %>.
    <% else %>
      Vote: -<%= micropost.downvote - micropost.upvote %>.
    <% end %>
  </span>
  <ol class="replies">
    <%= render micropost.replies %>
  </ol>
  <section class="reply_form">
    <%= form_for micropost.replies.build do |f| %>
      <%= hidden_field_tag :micropost_id, micropost.id %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.text_area :content, placeholder: "Leaving a reply..." %>
        </div>
      <%= f.submit "Reply", class: "btn btn-primary" %>
    <% end %>
  </section>
</li>